title: "Nenad Pantelić"
email: nenadpantelickg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Portfolio page for my MLH Fellowship journey. I was part of Open-Source track working with forem(dev.to)
  project. I've used Ruby and Ruby on Rails for the first time. It was an exciting and amazing journey. 
  See my results here.
baseurl: "/"
url: "/mlh-portfolio"
twitter_username:
github_username: NenadPantelic

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
